env:
  browser: true
  node: true
extends: 'eslint:recommended'
rules:
  no-undef:
    - 0
  indent:
    - error
    - tab
  linebreak-style:
    - 0
  quotes:
    - error
    - single
  semi:
    - error
    - always
